### ISSUE TITLE
invalid token problem

### ISSUE THREAD

**Issue by Mounthazeer** [JAXPARROW/testrepo#1]
hi i am getting Invalid verification token when adding /whatsapi to m heroku url
i really need help

**Comment by JAXPARROW** [comment]
Hi @Mounthazeer can you show me the snapshot/screen capture of the error you are getting, Plus I have updated the documentation for easier follow-up.

**Comment by Mounthazeer** [comment]
![testimg](https://user-images.githubusercontent.com/58270012/170907456-35392565-2b3f-46e4-81ad-53071ab32bcc.png)
i am getting this problem can you tell me what is wrong 
i did set the token variable to testing when configuring the variables in heroku

**Comment by Mounthazeer** [comment]
![image](https://user-images.githubusercontent.com/58270012/170907930-2e7121d3-9144-46e5-915b-3255b3cb763a.png)
there is also this when i try at product-webhooks in developer portal

**Comment by Mounthazeer** [comment]
![image](https://user-images.githubusercontent.com/58270012/170908376-99db6554-4c69-4ae4-904b-2916e8ed040c.png)
there is also this i try from product-webhooks in developer portal please help

**Comment by Mounthazeer** [comment]
the url  outputs 'hello it works' however if i put /whatsapi at the end it says invalid verification token and these are the errors i get above when trying to configure the webhook in the developer portal

**Comment by JAXPARROW** [comment]
> ![testimg](https://user-images.githubusercontent.com/58270012/170907456-35392565-2b3f-46e4-81ad-53071ab32bcc.png) i am getting this problem can you tell me what is wrong i did set the token variable to testing when configuring the variables in heroku

The verify token should be the same used in the Heroku environment config
