### ISSUE TITLE
Error on runtime.txt

### ISSUE THREAD

**Issue by jrenan** [JAXPARROW/testrepo#3]
When I try to deploy the app on Heroku I get the message

!     Requested runtime 'python-3.9.0' is not available for this stack (heroku-22).
 !     For supported versions, see: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by doiiido** [comment]
same here

**Comment by JAXPARROW** [comment]
I just updated the python stuck to the supported version for Heroku.

> When I try to deploy the app on Heroku I get the message
> 
> ! Requested runtime 'python-3.9.0' is not available for this stack (heroku-22). ! For supported versions, see: https://devcenter.heroku.com/articles/python-support ! Push rejected, failed to compile Python app. ! Push failed

I just updated the python stuck to the supported version for Heroku.

**Comment by JAXPARROW** [comment]
> same here

I just updated the python stuck to the supported version for Heroku.

**Comment by JAXPARROW** [comment]
I just updated the python stuck to the supported version for Heroku.
